### ISSUE TITLE
SLAM这一栏新增一篇cvpr2024录用paper 的建议

### ISSUE THREAD

**Issue by frank-fyf** [52CV/CVPR-2024-Papers#1]
https://arxiv.org/pdf/2312.01616.pdf
https://github.com/bytedance/SchurVINS
SchurVINS: Schur Complement-Based Lightweight Visual Inertial Navigation System
这篇paper已被CVPR2024录用，建议加入到CVPR-2024-Papers的SLAM这一栏中。
![image](https://github.com/52CV/CVPR-2024-Papers/assets/163279145/c33b31ee-eeb3-4793-abf1-cd938af3c85b)

**Comment by 52CV** [comment]
收到
